const KEY_NAME = 'naijamed_gemini_api_key';

export function hasGeminiKey(): boolean {
  if (typeof window === 'undefined') return false;
  return !!localStorage.getItem(KEY_NAME);
}

export function saveGeminiKey(key: string): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(KEY_NAME, key.trim());
}

export function getGeminiKey(): string | null {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem(KEY_NAME);
}

export function removeGeminiKey(): void {
  if (typeof window === 'undefined') return;
  localStorage.removeItem(KEY_NAME);
}

async function callGeminiApi(prompt: string, systemInstruction: string, history?: { role: 'user' | 'model'; parts: { text: string }[] }[]): Promise<string> {
  const apiKey = getGeminiKey();
  if (!apiKey) {
    throw new Error("Gemini API key is not configured. Please add it in Settings.");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
  
  // Format contents. If history is provided, use it. Otherwise, single prompt.
  let contents = [];
  if (history && history.length > 0) {
    contents = [...history, { role: 'user', parts: [{ text: prompt }] }];
  } else {
    contents = [{ role: 'user', parts: [{ text: prompt }] }];
  }

  const payload = {
    contents,
    systemInstruction: {
      parts: [
        {
          text: systemInstruction
        }
      ]
    },
    generationConfig: {
      temperature: 0.3,
      maxOutputTokens: 1024,
    }
  };

  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const errMsg = errData.error?.message || `HTTP error! status: ${response.status}`;
      throw new Error(errMsg);
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText) {
      throw new Error("No response content generated by Gemini.");
    }

    return candidateText;
  } catch (error: any) {
    console.error("Gemini API Call failed:", error);
    throw error;
  }
}

/**
 * Translates clinical drug-drug interactions into simplified, plain English and Pidgin.
 */
export async function explainInteractionWithAi(drugA: string, drugB: string, clinicalDescription: string): Promise<string> {
  const systemInstruction = `You are a friendly, expert Nigerian pharmacist. Your goal is to explain drug-drug interactions in plain, non-scary, and accessible English, followed by a summary in Nigerian Pidgin.
Highlight:
1. What the user might feel or experience (e.g., dizziness, stomach burn, drowsiness).
2. Practical steps to take (e.g., space them out, stop one, talk to a pharmacist/doctor).
3. Warn about common local habits (e.g., combining pain pills like Felvin and Cataflam, or drinking alcohol with Flagyl).
4. Keep it clear, informative, and visually readable with headings or bullet points. Avoid clinical jargon.`;

  const prompt = `A patient is taking: "${drugA}" and "${drugB}".
The scientific clinical database lists this interaction description: "${clinicalDescription}".
Please explain what this means in simple English and Nigerian Pidgin.`;

  return callGeminiApi(prompt, systemInstruction);
}

/**
 * Provides a context-aware analysis of symptoms with focus on common conditions in Nigeria.
 */
export async function analyzeSymptomsWithAi(symptoms: string): Promise<string> {
  const systemInstruction = `You are a friendly, expert Nigerian physician analyzing symptoms in a triage context.
Your goals:
1. Provide a plain-language analysis of the symptoms. Point out possible causes, giving attention to diseases common in Nigeria (such as malaria, typhoid, food poisoning, Lassa fever, cholera, or general dehydration) if relevant.
2. Outline key questions they should think about (e.g., "Have you been exposed to mosquitoes?", "Is there a cholera outbreak in your area?").
3. CRITICAL: List 'Red Flag' symptoms that require running to a clinic or hospital immediately (e.g., stiff neck, difficulty breathing, high fever lasting >3 days, blood in stool, severe dehydration).
4. Provide a warm, actionable summary in Nigerian Pidgin.
5. Emphasize a strict medical disclaimer: You are an AI, not a doctor. They must seek professional care. Do not make an absolute diagnosis.`;

  const prompt = `A user reports the following symptoms: "${symptoms}".
Please analyze this, highlight potential local conditions, outline red flags, and summarize in Pidgin.`;

  return callGeminiApi(prompt, systemInstruction);
}

/**
 * Free-form chat with a localized AI health companion.
 */
export async function chatWithAi(
  history: { role: 'user' | 'model'; parts: { text: string }[] }[],
  newMessage: string
): Promise<string> {
  const systemInstruction = `You are "NaijaMed AI", a friendly, empathetic health companion for Nigerians.
You explain medical concepts simply, using plain English and conversational Nigerian Pidgin where helpful.
Guidelines:
1. Offer advice on drugs, active ingredients, dosage directions, and side effects based on general pharmacy practice.
2. Advise users on typical Nigerian brand names (e.g., Emzor Paracetamol, Coartem, Lokmal, Felvin, Septrin) and warning flags.
3. Strongly discourage self-medication for complex illnesses. Recommend testing (e.g., Rapid Diagnostic Test for malaria, blood culture for typhoid) instead of swallowing pills blindly.
4. Educate users on checking NAFDAC verification scratch cards on drugs.
5. End or include a gentle warning that you are an AI helper, not a substitute for a doctor's examination.`;

  return callGeminiApi(newMessage, systemInstruction, history);
}
